# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('cmsplugin_facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPagePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_facebook_facebookpageplugin', serialize=False, to='cms.CMSPlugin')),
                ('pageurl', models.URLField(blank=True, help_text="If blank, the page where it's displayed will be used.", null=True, verbose_name='URL to like')),
                ('width', models.PositiveSmallIntegerField(blank=True, default=None, help_text='Leave empty for auto scaling.', null=True, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='facebooklikebox',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='facebooklikebutton',
            name='font',
        ),
        migrations.RemoveField(
            model_name='facebooklikebutton',
            name='height',
        ),
        migrations.AlterField(
            model_name='facebooklikebutton',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_facebook_facebooklikebutton', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='facebooklikebutton',
            name='color_scheme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=50, verbose_name='Color Scheme'),
        ),
        migrations.AlterField(
            model_name='facebooklikebutton',
            name='layout',
            field=models.CharField(choices=[('standard', 'standard'), ('button_count', 'button count'), ('button', 'button'), ('box_count', 'box count')], default='standard', max_length=50, verbose_name='Layout Style'),
        ),
        migrations.AlterField(
            model_name='facebooklikebutton',
            name='verb',
            field=models.CharField(choices=[('like', 'like'), ('recommend', 'recommend')], default='like', max_length=50, verbose_name='Verb to display'),
        ),
        migrations.DeleteModel(
            name='FacebookLikeBox',
        ),
    ]
